valor = int(input('Digite o valor para obter a tabuada: '))
print('*'*12)
print(f'{valor} * {1:2} = {valor * 1}')
print(f'{valor} * {2:2} = {valor * 2}')
print(f'{valor} * {3:2} = {valor * 3}')
print(f'{valor} * {4:2} = {valor * 4}')
print(f'{valor} * {5:2} = {valor * 5}')
print(f'{valor} * {6:2} = {valor * 6}')
print(f'{valor} * {7:2} = {valor * 7}')
print(f'{valor} * {8:2} = {valor * 8}')
print(f'{valor} * {9:2} = {valor * 9}')
print(f'{valor} * {10:2} = {valor * 10}')
print('*'*12)
